// This file is generated by Slice Machine. Update with care!

import BannerSlice from './BannerSlice';
import FeaturedImage from './FeaturedImage';
import FullWidthImage from './FullWidthImage';
import ImageGallery from './ImageGallery';
import MedalliaTopPartOne from './MedalliaTopPartOne';
import QuoteSlice from './QuoteSlice';
import TextSlice from './TextSlice';

export {
	BannerSlice,
	FeaturedImage,
	FullWidthImage,
	ImageGallery,
	MedalliaTopPartOne,
	QuoteSlice,
	TextSlice,
};

export const components = {
	banner_slice: BannerSlice,
	featured_image: FeaturedImage,
	full_width_image: FullWidthImage,
	image_gallery: ImageGallery,
	medallia_top_part_one: MedalliaTopPartOne,
	quote_slice: QuoteSlice,
	text_slice: TextSlice,
};
